version: 2
registries:
  git-gitlab-yeebase-com:
    type: git
    url: https://gitlab.yeebase.com
    username: jsu
    password: "${{secrets.GIT_GITLAB_YEEBASE_COM_PASSWORD}}"
  git-github-com:
    type: git
    url: https://github.com
    username: x-access-token
    password: "${{secrets.GIT_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/e2e"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@testing-library/cypress"
    versions:
    - 7.0.3
    - 7.0.4
    - 7.0.5
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  registries:
  - git-gitlab-yeebase-com
  - git-github-com
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  target-branch: master
  registries:
  - git-gitlab-yeebase-com
  - git-github-com
